controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    # 1. 机械臂本体控制器
    fr5_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # 2. 夹爪控制器 (🌟 修改为联合位置控制器)
    gripper_controller:
      type: position_controllers/JointGroupPositionController

    # 3. 状态发布器
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# ------------------------------------------------------------------
# 机械臂控制器参数 (纯位置控制，仿真中绝对不会下垂)
# ------------------------------------------------------------------
fr5_joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    
    # 强制指定为 position 接口
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    # 开启开环控制，Gazebo 会强制将位置指令写入物理引擎
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0

# ------------------------------------------------------------------
# 夹爪控制器参数
# ------------------------------------------------------------------
gripper_controller:
  ros__parameters:
    # 🌟 同时下发指令给左指和右指，真正实现对称夹取
    joints:
      - left_finger_joint
      - right_finger_joint
    interface_name: position